[project]
name = "mnist-subliminal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "jax>=0.7.0",
    "numpy>=2.3.2",
    "tensorflow>=2.20.0",
]
